### ISSUE TITLE
kafka does not works 

### ISSUE THREAD

**Issue by fabiofumarola** [DataToKnowledge/dockerfile#3]
I tried with 3 configurations of kafka. The third one is totally correct and with minimal configuration. I tested the configuration having a zookeeper node started in foreground to see what kafka send as request. 

```
node_1 | 2015-06-17 07:24:07,309 [myid:] - INFO  [ProcessThread(sid:0 cport:-1)::PrepRequestProcessor@645] - Got user-level KeeperException when processing sessionid:0x14e00654c880003 type:create cxid:0x31 zxid:0x23 txntype:-1 reqpath:n/a Error Path:/brokers/topics/test/partitions/1 Error:KeeperErrorCode = NoNode for /brokers/topics/test/partitions/1
node_1 | 2015-06-17 07:24:07,314 [myid:] - INFO  [ProcessThread(sid:0 cport:-1)::PrepRequestProcessor@645] - Got user-level KeeperException when processing sessionid:0x14e00654c880003 type:create cxid:0x32 zxid:0x24 txntype:-1 reqpath:n/a Error Path:/brokers/topics/test/partitions Error:KeeperErrorCode = NoNode for /brokers/topics/test/partitions
node_1 | 2015-06-17 07:24:07,336 [myid:] - INFO  [ProcessThread(sid:0 cport:-1)::PrepRequestProcessor@645] - Got user-level KeeperException when processing sessionid:0x14e00654c880003 type:create cxid:0x36 zxid:0x28 txntype:-1 reqpath:n/a Error Path:/brokers/topics/test/partitions/0 Error:KeeperErrorCode = NoNode for /brokers/topics/test/partitions/0
```

it is clear that during kafka startup there are some problems on creating configurations on zookeeper. At this point I give you room for a try.

What I found weird is that:
1. if you try to restart kafka using the same data folder it give you an error (so we cannot use kafka in a safe way)
2. it is very hard to configure with docker

I'm sure that there is some error when kafka startup and send messages to zookeeper to setup the initial configurations. At this point I'm thinking that kafka requires to much time in configurations setting and also if we setup a simple kafka node using some already one docker it will create a lot of problems. Maybe we should use some other alternative.

**Comment by fabiofumarola** [comment]
Dopo un altro test ho capito che il problema e' sui nomi degli hosts e le porte. Se non sono configurati propriamente non funziona. Ti cedo il task, ti consiglio di utilizzare porte standard per la comunicazione

**Comment by fabiofumarola** [comment]
Ok Ho trovato il problema e' nelle configurazioni delle porte per ora lascerei tutto configurato con le porte standard

**Comment by fabiofumarola** [comment]
Per piacere puoi ripulire tu tutti i docker, per ora il servizio funziona sulla backend-1 utilizzando:
1. il nostro docker con zookeeper
2. e la seguente conf

```
docker run -d --name kafka --volume /data/kafka/data:/data --volume /data/kafka/logs:/logs --publish 9092:9092 --publish 7203:7203 --env EXPOSED_HOST=xxx.cloudapp.net --env ZOOKEEPER_IP=xxx-1.cloudapp.net --env ZOOKEEPER_PORT=2181 plasmap/kafka
```

**Comment by Gigitsu** [comment]
Ok me la vedo io
